default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: 1234
  database: myapp_development

development:
  <<: *default

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production